# 변수정의 Variable Dictionary # 

### 새 개념
- int / float / str ' ' / list[ ] / tuple( ) / dict{ }

- type(a) / print(a) / a[0] / a[-1]

- import / numpy / np / array / matrix / Transpose

In [3]:
a=1

a : 변수(variable)

1 : 내용(content)

In [1]:
a=1;b=2

In [2]:
a
b

2

맨 마지막 b 만 보여줌

둘 다 보고 싶으면 print 기능 사용하거나  or  각각 다른 cell 에 a,b 각각 입력

In [4]:
print(a)
print(b)

1
2


#### 1. int : 정수

각 variable은 type 정해져 있지만 내 설정따라 변할 수 있음

In [5]:
type(a)

int

#### 2. float : 소수점 있는 것

In [7]:
a = 1.0

In [8]:
type (a)

float

#### Type 바꾸기 → 처음부터 내가 설정

비록 float 이지만 type을 int로 설정해서 실행하면 1로 뜨는 것

In [9]:
int(a)

1

In [10]:
a = 1.1
type(a)

float

In [11]:
int(a)

1

1로 결과 나오지만 실제 값은 1.1인것(유지됨)

In [12]:
float(int(a))

1.0

In [13]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [14]:
a = 1; a = float(a); type(a)

float

print(type(a)) 하면 결과값이 class로 뜨고

그냥 type(a) 로 하면 바로 결과값이 뜸

In [15]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [16]:
a = 1.2; a = int(a); print(a)

1


#### 3. str : string 

→ ' ' / " " 둘 중 뭘 쓰든 상관없 / string 내에서 띄어쓰기 하던말던 상관없

In [2]:
a = '1 2 3'; print(type(a))

<class 'str'>


In [29]:
a = 'abc'

In [1]:
a = 'a b c'; print(type(a))

<class 'str'>


In [1]:
a = 'abc'; print(type(a))

<class 'str'>


In [31]:
a[1]; a[0]; a[-1]

'c'

In [32]:
print(a[1])
print(a[0])
print(a[-1])

b
a
c


<순서> 

- 0이 첫번째 (1이 첫번째 아님 주의)

- 1이 두번째

- -1은 항상 몇개가 있든 맨 끝을 의미

#### 4. list : 대괄호[ ]사용 / comma로 분리

In [34]:
a = '123'
a = [1,2,3]; type(a)

list

<비교>

- a = '123' → 문자 (string)

- a = [1,2,3] → 숫자 (list)

In [35]:
a = [1,2,a]; a = [1,2,'ab',[4,5]]

In [1]:
a = [1,2,'ab',[4,5]]; print(a[2])

ab


list는 무한히 확장 가능 / 자료의 삽입or삭제가 용이

→ list안에 str들어가고 되고 또 다른 list 넣어도 가능

In [2]:
 a = [1,2,'ab',[4,5]]; print(a[-1]); print(a[-1][0])

[4, 5]
4


In [40]:
a = '123'; a = list(a); print(a)

['1', '2', '3']


→ Type 바꾸기

#### 종합연습

In [43]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [2]:
a = [1,'2', [3, '4']]; a[1]

'2'

string 을 

그냥 a[1] 로 하면 ' ' 포함해서 값이 나오고

print(a[1])로 하면 ' ' 빼고 값만 나옴

#### 5. tuple : ( ) 사용

→ list보다 바꾸기 힘든 특성 but 거의 같다고봐도 무방

In [44]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


#### 6. dict : { }사용 / pairwise 특성

- print(a["a"]) 의 값이 apple임

- index로 접근하는게 아니라 표제어 "a"(key값) 로 접근 

- list[ ]나 tuple() 쓰는게 index로 접근하는 방법 → indexing (=array 의 특정 위치만 짜르기) 

In [45]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### 또 다른 예시

In [5]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

list 안에 tuple로 구성

→ 행렬과 같은 특성 

→ 2by3 행렬 (모양만 차용)

#### 7. import 기능

- 하드디스크에 저장(다운)하는 듯한 기능
- 메모리에 올려놓는 것 / package 불러오는것

→ numpy는 basic으로 들어와있지 않아서 memory로 띄워야하는 것

#### 8. numpy
- 파이썬을 계산 혹은 분석에 이용할 때 쓰는 핵심 역할을 하는 라이브러리 중 하나

#### 9. array 함수
- ndarray : array 함수로 만든 다차원 배열의 데이터 타입


In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


→ 설명 : numpy디렉토리에 있는 모든 것을 띠워라 (numpy는 하나의 폴더)
- as np 쓰지 않으면 밑에처럼 써야함 
- as np = 메모리로 띠우자

→ b = numpy라는 폴더 안에 있는 array 라는 함수를 쓰자

→ class = numpy 폴더에 n-dimensional array 함수(=ndarray) 

→ 진짜 2by3 행렬 모양이 나옴

In [ ]:
import numpy 
b = nunmpy.array(a)
print(b)
print(type(b))

In [3]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


→ array 가 진짜 행렬이면 2by3 × 2by3 은 불가능 (2by3 이면 3by 형태여야함)

but) 모양만 행렬이기에 element 끼리 곱해짐

#### 10. matrix 함수 
- array와 조금 다름 (약간 행렬같이 in 연산 결과)

In [4]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

→ 행렬같은 특성 때문에 곱하기 안됌

In [6]:
c*c.T

matrix([[14, 19],
        [19, 73]])

#### 11. Transpose기능 
→ 2by3 를 3by2로 바꿔줬기 때문에 곱하기 가능해짐
- 사용법 :  .을 쓰고 뒤에 기능 써주기 (class 이기에 쓸 수 있는 기능)

  → variable 보다 조금 확장된 게 class ex) string class
  
  
- Transpose기능이 파이썬 자체에 있는 건 아니고 numpy에 있는 기능임

## <주요 단축키> 
1.cell의 왼쪽 빈공간 + a = 위쪽에 새로운 cell 생성

2.cell의 왼쪽        + b = 아래에 새로운 cell 생성

3.cell의 왼쪽        + x = cell 삭제

4.shift + Enter   = run (실행) / alt + Enter = 현재 셀 실행하고 아래 새로운 셀 추가

5.# = 글자 크기 조절. 많이 쓸수록 작아짐

6.결과값 숨기기 = 왼쪽 아래부분 더블클릭

7.ctrl + s = 저장

8.ctrl + / = code셀에서 주석처리 시키는 것 

   = 작은or큰 따옴표 ''' ''' 앞뒤로 넣어주면 됌 or 앞에 # 넣기
 
9.마크다운 상태에서 왼쪽바 눌러놓고 # 원하는 개수 쳐주면 일일이 입력안해도 바로 입력됨

질문은 github에서 repository내 issue에서 글 올리기